### ISSUE TITLE
Crash when entering a bus, coming from OpenAL Soft 1.15.1

### ISSUE THREAD

**Issue by Bob-Z** [RigsOfRods/ror-linux-buildscripts#1]
Not sure if this is the right place for this, anyway, here it is.
I am using Ubuntu 14.10 64 bits, compiling dependencies and RoR with your scripts (and many thanks for that by the way).
When trying to drive bus "RVI Agora L" by pressing Enter nearby, the game crash.
I tried to have a back trace but it was corrupted.
So I made a run with valgrind and it show that openal is doing nasty things:

==16680== Thread 8:
==16680== Invalid read of size 16
==16680==    at 0x69D5C66: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69D4316: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69CAF6E: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69DBC4B: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69CF9D9: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x5B750A4: start_thread (pthread_create.c:309)
==16680==    by 0x808088C: clone (clone.S:111)
==16680==  Address 0x21cd1570 is 99,104 bytes inside a block of size 99,119 alloc'd
==16680==    at 0x4C2D136: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16680==    by 0x4C2D251: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16680==    by 0x69CFF14: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69CFF4D: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69C5000: alcOpenDevice (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x500494: SoundManager::SoundManager() (in/tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x50A75A: SoundScriptManager::SoundScriptManager() (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x837E33: RoR::ContentManager::init() (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x85B65E: RoR::MainThread::Go() (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x4FD834: main (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680== 
==16680== Invalid write of size 8
==16680==    at 0x69D5C69: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69D4316: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69CAF6E: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69DBC4B: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69CF9D9: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x5B750A4: start_thread (pthread_create.c:309)
==16680==    by 0x808088C: clone (clone.S:111)
==16680==  Address 0x21cd1578 is 99,112 bytes inside a block of size 99,119 alloc'd
==16680==    at 0x4C2D136: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16680==    by 0x4C2D251: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16680==    by 0x69CFF14: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69CFF4D: ??? (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x69C5000: alcOpenDevice (in /usr/lib/x86_64-linux-gnu/libopenal.so.1.15.1)
==16680==    by 0x500494: SoundManager::SoundManager() (in /media/2To/jeux/linux/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x50A75A: SoundScriptManager::SoundScriptManager() (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x837E33: RoR::ContentManager::init() (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x85B65E: RoR::MainThread::Go() (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)
==16680==    by 0x4FD834: main (in /tmp/rigsofrods/rigs-of-rods/bin/RoR)

So I tried to update openal. Ubuntu repository version is 1.15.1 as you can see above, so I tried 1.16.0 from GIT repository:

git clone http://repo.or.cz/openal-soft.git
cd openal-soft
git checkout tags/openal-soft-1.16.0
cmake .
make
sudo make install

Then I recompiled RoR, and this was a fix ! Moreover, unsurprisingly, the game seems to be more stable.

I guess you should add openal as one of the dependencies in your script, until official repository update their openal version.

I have not proposed a pull request because I am unsure of which dependencies openal needs in the RoR scope. On my system here is the cmake output:

-- Could NOT find FluidSynth (missing:  FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR) 
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.0.28") 
-- Found OSS: /usr/include/x86_64-linux-gnu  
-- Could NOT find AudioIO (missing:  AUDIOIO_INCLUDE_DIR) 
-- Could NOT find SoundIO (missing:  SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR) 
-- Could NOT find QSA (missing:  QSA_LIBRARY QSA_INCLUDE_DIR) 
-- Found PortAudio: /usr/lib/x86_64-linux-gnu/libportaudio.so  
-- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so (found version "4.0.0") 
-- Looking for include files SLES/OpenSLES.h, SLES/OpenSLES_Android.h
-- Looking for include files SLES/OpenSLES.h, SLES/OpenSLES_Android.h - not found
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.8.0") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so  
-- Could NOT find SDL_sound (missing:  SDL_SOUND_LIBRARIES SDL_SOUND_INCLUDE_DIR) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'libavcodec'
--   found libavcodec, version 56.1.0
-- checking for module 'libavformat'
--   found libavformat, version 56.1.0
-- checking for module 'libavdevice'
--   package 'libavdevice' not found
-- checking for module 'libavutil'
--   found libavutil, version 54.3.0
-- checking for module 'libswscale'
--   found libswscale, version 3.0.0
-- checking for module 'libswresample'
--   package 'libswresample' not found
-- checking for module 'libpostproc'
--   package 'libpostproc' not found
## -- Could NOT find FFmpeg (missing:  SWRESAMPLE_LIBRARIES SWRESAMPLE_INCLUDE_DIRS) 

-- Building OpenAL with support for the following backends:
## --      ALSA, OSS, PortAudio, PulseAudio, WaveFile, Null

-- Building with support for CPU extensions:
--     Default, SSE, SSE2, SSE4.1

Even without all dependencies being found, this works for me.
I hope this helps.

**Comment by Hiradur** [comment]
Did you have HRTF enabled?

**Comment by Bob-Z** [comment]
How do I know this ?
Is the presence of ALC_SOFTX_HRTF in hte following output answer your question ?

$ openal-info 
Available playback devices:
    Built-in Audio Analog Stereo
Available capture devices:
    Built-in Audio Analog Stereo
    QuickCam Messenger Analog Mono
    Monitor of Built-in Audio Analog Stereo
Default playback device: Built-in Audio Analog Stereo
Default capture device: Built-in Audio Analog Stereo
ALC version: 1.1

*\* Info for device "Built-in Audio Analog Stereo" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE,
    ALC_EXT_DEDICATED, ALC_EXT_disconnect, ALC_EXT_EFX,
    ALC_EXT_thread_local_context, ALC_SOFTX_device_clock, ALC_SOFTX_HRTF,
    ALC_SOFT_loopback, ALC_SOFTX_midi_interface, ALC_SOFT_pause_device
OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.16.0
OpenAL extensions:
    AL_EXT_ALAW, AL_EXT_DOUBLE, AL_EXT_EXPONENT_DISTANCE, AL_EXT_FLOAT32,
    AL_EXT_IMA4, AL_EXT_LINEAR_DISTANCE, AL_EXT_MCFORMATS, AL_EXT_MULAW,
    AL_EXT_MULAW_MCFORMATS, AL_EXT_OFFSET, AL_EXT_source_distance_model,
    AL_LOKI_quadriphonic, AL_SOFT_block_alignment, AL_SOFT_buffer_samples,
    AL_SOFT_buffer_sub_data, AL_SOFT_deferred_updates, AL_SOFT_direct_channels,
    AL_SOFT_loop_points, AL_SOFT_MSADPCM, AL_SOFT_source_latency,
    AL_SOFT_source_length
EFX version: 1.0
Max auxiliary sends: 4
Supported filters:
    Low-pass, High-pass, Band-pass
Supported effects:
    EAX Reverb, Reverb, Chorus, Distortion, Echo, Flanger, Ring Modulator,
    Compressor, Equalizer, Dedicated Dialog, Dedicated LFE

**Comment by Hiradur** [comment]
No, this just means that it is supported in your OpenAL version. You have to set it manually in the config file (or another program sets it for you). Have a look at /etc/openal/alsoft.conf and ~/.alsoftrc and see if you can find a line like

```
hrtf = true
```

**Comment by Bob-Z** [comment]
hrtf seems disabled here.

in /etc/openal/alsoft.conf:
#hrtf = false

I have no ~/.alsoftrc

**Comment by Hiradur** [comment]
Ok, I asked because 1.15.1 was known to crash with HRTF turned on.
I think I won't add OpenAL from GitHub to the dependecies script though because Ubuntu 14.04 LTS still uses OAL 1.14 and thus is safe and the next Ubuntu non-LTS release will probably include 1.16. I don't want to mess with the OpenAL installation that comes with the distro unless it is really necessary. Thanks for reporting though, maybe it helps someone else.

**Comment by rot13** [comment]
To Bob-Z: nice find, thanks, I added OpenAL to my version.
To Hiradur: thank you for your scripts, very helpful. I moved apt-get commands to a separate script, and modified other scripts to not require root - everything is installed to user's home without using sudo. Check out my fork. What do you think? Would you like to merge these changes? Should I do a pull request?

**Comment by Hiradur** [comment]
@rot13 I had a quick look and the changes look good! I will have to test them on a VM first but I'm open for a pull request.

**Comment by Hiradur** [comment]
Since OpenAL 1.16 is now built by the script as well I'll close this.
