### ISSUE TITLE
unable to update ror

### ISSUE THREAD

**Issue by consultit** [RigsOfRods/ror-linux-buildscripts#10]
I'm trying to update ror by executing the command "sh core.sh" but I get this error:

...
CMake Error at source/version_info/CMakeLists.txt:45 (add_library):
  Cannot find source file:

```
/home/consultit/rigs-of-rods/source/rigs-of-rods/0_build/RelWithDebInfo/source/version_info/version_info.cpp
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Build files have been written to: /home/marco/rigs-of-rods/source/rigs-of-rods/0_build/RelWithDebInfo
...

**Comment by Hiradur** [comment]
I also had this error on an install I haven't updated for a long while. I couldn't find the cause of the problem but deleting the RoR folder and doing a fresh clone helped.

**Comment by consultit** [comment]
I tried both to clear the RoR folder and to reinstall everything but unfortunately the problem persists. It may be the version of cmake? I have the 3.0.2.

**Comment by Hiradur** [comment]
> It may be the version of cmake? I have the 3.0.2.

3.0.2 should be enough: https://github.com/RigsOfRods/rigs-of-rods/blob/master/CMakeLists.txt#L1

**Comment by Hiradur** [comment]
I just had the same error on a Raspberry Pi 2. I was able to make it work by creating an empty file called `version_info.cpp` at the place where CMake is looking. The file will then be filled by CMake with the necessary info.

**Comment by consultit** [comment]
This workaround worked, now I can build and run ror properly. 
Thanks
