### ISSUE TITLE
Error while loading shared library libOgrePaging.so.1.9.0 (Ubuntu 17.04)

### ISSUE THREAD

**Issue by RAD750** [RigsOfRods/ror-linux-buildscripts#13]
Hello,
I have installed RoR with your scripts which seemed to work perfectly (no errors at all).
I can run the configurator with no problems, but when I click on "save and load" it crashes.
If I launch RoR directly from command line, I get this:
```
jacopo@ubuntu:~/rigs-of-rods/install/bin$ ./RoR
./RoR: error while loading shared libraries: libOgrePaging.so.1.9.0: cannot open shared object file: No such file or directory

```
Is this something related to Ubuntu 17.04 or something else broke?
I am sure I ran all the scripts in order...
Is there any other file I can send or things I can do to troubleshoot the problem?

By the way, I had to modify the content.sh script with the new URLs, since it gave me a 404 error. The URL apparently changed from downloadcdn.rigsofrods.org to dl.rigsofrods.org ;-)

Thanks in advance for troubleshooting.

**Comment by Ninja5tyl3** [comment]
I am also having this error when trying to run the game.  I am also running Ubuntu 17.04.

**Comment by ohlidalp** [comment]
Hello.

**UPDATE1:**
Search the OGRE build directory for file "libOgrePaging.so*". If you find it, try copying it to the directory where "RoR" binary is located. If you don't find it, find and post "CMakeCache.txt" file so I can take a look if the module was even selected for building. Then I'll need to see OGRE's build log if you can find it, but I can't guide you - I don't know where it's saved.

**ORIG POST:**
I'm not familiar with the linux scripts (I'm a Windows developer), but my guesses are:
* Maybe Ubuntu has "OgrePaging" component in a separate package and you don't have it installed.
* Maybe Ubuntu's OGRE packages are broken and the paging component cannot be loaded.
* Maybe there's a bug in the scripts.

I'll get back with more info.

**Comment by Ninja5tyl3** [comment]
I tried moving libOgrePaging.so and libOgrePaging.so.1.9.0 to the RoR binary and kept getting the same error.  I have both the Rigs of Rods CMakeCache.txt and the Ogre CMakeCache.txt
[Rigs Of Rods CMakeCache.txt](https://github.com/RigsOfRods/ror-linux-buildscripts/files/1191943/Rigs.Of.Rods.CMakeCache.txt)
[Ogre CMakeCache.txt](https://github.com/RigsOfRods/ror-linux-buildscripts/files/1191945/Ogre.CMakeCache.txt)

**Comment by ohlidalp** [comment]
@Ninja5tyl3 Use http://man7.org/linux/man-pages/man1/ldd.1.html to see what *.so files RoR requires and where is it looking for them.

Also try:
- https://unix.stackexchange.com/questions/58846/viewing-linux-library-executable-version-info
- https://www.cyberciti.biz/tips/linux-shared-library-management.html

**Comment by Ninja5tyl3** [comment]
Figured out what is happening.  libOgrePaging.so and libOgrePaging.so.1.9.0 are located in "wherever-RoR-is-installed/install/lib/" while the executable is looking in "/usr/lib/x86_64-linux-gnu/".  Moving the libraries there fixes the issue and the game runs.

**Comment by ShannonVanWagner** [comment]
@Ninja5tyl3 - Fantastic work!! This makes 1ea 7 year old (and Dad too) very very happy that they can play the game again. Thanks for posting the fix. Cheers.
