### ISSUE TITLE
game.sh error and deleted bin

### ISSUE THREAD

**Issue by saltzstang** [RigsOfRods/ror-linux-buildscripts#24]
/ror-linux-buildscripts-master$ sh game.sh
Already up-to-date.
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for OIS...
-- Found OIS: /usr/lib/x86_64-linux-gnu/libOIS.so
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for OIS...
-- Found OIS: /usr/lib/x86_64-linux-gnu/libOIS.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/logan/rigs-of-rods-source/rigs-of-rods/0_build/RelWithDebInfo
[  1%] Generate files containing version information
[  5%] Built target angelscript_addons
[  5%] Built target generate_version
Scanning dependencies of target version_info
[  5%] Building CXX object source/version_info/CMakeFiles/version_info.dir/version_info.cpp.o
[  6%] Linking CXX static library ../../bin/libversion_info.a
[  6%] Built target version_info
[  7%] Linking CXX executable ../../bin/RoRConfig
[ 10%] Built target RoRConfig
[ 10%] Linking CXX executable ../../bin/RoR
Zip and copy resources to build directory
Traceback (most recent call last):
  File "/home/logan/rigs-of-rods-source/rigs-of-rods/tools/recursive_zipper.py", line 62, in <module>
    recursive_zipper(args.work_directory, args.out_directory)
  File "/home/logan/rigs-of-rods-source/rigs-of-rods/tools/recursive_zipper.py", line 44, in recursive_zipper
    shutil.rmtree(zipdir)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'scripts.zip'
source/main/CMakeFiles/RoR.dir/build.make:4926: recipe for target 'bin/RoR' failed
make[2]: *** [bin/RoR] Error 1
make[2]: *** Deleting file 'bin/RoR'
CMakeFiles/Makefile2:201: recipe for target 'source/main/CMakeFiles/RoR.dir/all' failed
make[1]: *** [source/main/CMakeFiles/RoR.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AnotherFoxGuy** [comment]
There is a bug in the cmake that ships with Ubuntu, you need to install a newer version of cmake.
```
sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update
sudo apt-get install cmake 
```

**Comment by saltzstang** [comment]
rerun dependencies 16.04 after that?

**Comment by saltzstang** [comment]
Looks like same error afer running dependencies and game after those commands
sh game.sh 
Already up-to-date.
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for OIS...
-- Found OIS: /usr/lib/x86_64-linux-gnu/libOIS.so
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for OIS...
-- Found OIS: /usr/lib/x86_64-linux-gnu/libOIS.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/logan/rigs-of-rods-source/rigs-of-rods/0_build/RelWithDebInfo
[  1%] Generate files containing version information
[  5%] Built target angelscript_addons
[  5%] Built target generate_version
Scanning dependencies of target version_info
[  5%] Building CXX object source/version_info/CMakeFiles/version_info.dir/version_info.cpp.o
[  6%] Linking CXX static library ../../bin/libversion_info.a
[  6%] Built target version_info
[  7%] Linking CXX executable ../../bin/RoRConfig
[  7%] Linking CXX executable ../../bin/RoR
[ 10%] Built target RoRConfig
Zip and copy resources to build directory
Traceback (most recent call last):
  File "/home/logan/rigs-of-rods-source/rigs-of-rods/tools/recursive_zipper.py", line 62, in <module>
    recursive_zipper(args.work_directory, args.out_directory)
  File "/home/logan/rigs-of-rods-source/rigs-of-rods/tools/recursive_zipper.py", line 44, in recursive_zipper
    shutil.rmtree(zipdir)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'scripts.zip'
source/main/CMakeFiles/RoR.dir/build.make:4926: recipe for target 'bin/RoR' failed
make[2]: *** [bin/RoR] Error 1
make[2]: *** Deleting file 'bin/RoR'
CMakeFiles/Makefile2:201: recipe for target 'source/main/CMakeFiles/RoR.dir/all' failed
make[1]: *** [source/main/CMakeFiles/RoR.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
