### ISSUE TITLE
Setup Travis-CI autobuild for build AppImage automaticaly

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/ror-linux-buildscripts#25]
Please, setup `.travis.yml` for build and provide AppImage using Travis CI as OBS.
* https://github.com/AppImage/AppImageKit
  * https://github.com/AppImage/AppImages
* https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci
  * https://github.com/probonopd/uploadtool

Cast, @probonopd

**Comment by probonopd** [comment]
Happy to help if the ror-linux-buildscripts project is running into issues doing it.

**Comment by ohlidalp** [comment]
Hello, thanks for the suggestion and offer of help.

Unfortunately, I won't be of much help anytime soon, see also https://github.com/RigsOfRods/rigs-of-rods/issues/1411#issuecomment-345977459

**Comment by probonopd** [comment]
How did you produce the AppImage? It is missing libraries:

```
$ export LD_LIBRARY_PATH=squashfs-root/usr/lib/ ; ldd squashfs-root/usr/bin/RoR | grep not
	libfreeimage.so.3 => not found
	libzzip-0.so.13 => not found
```
