### ISSUE TITLE
issues building on debian

### ISSUE THREAD

**Issue by consultit** [RigsOfRods/ror-linux-buildscripts#39]
I just tried to build `ror` on my debian stretch box using the most recent commit.
After fixing both `dependencies.sh` and` game.sh` (I have attached a [patch](https://github.com/RigsOfRods/ror-linux-buildscripts/files/2948270/fix.patch.txt) created with `git diff`), I've run:
```
sh dependencies.sh
sh game.sh
```
and everything worked fine until linking, when I got these [errors](https://github.com/RigsOfRods/ror-linux-buildscripts/files/2948284/errors.txt).
Unfortunately I'm not an expert in the building system (conan/cmake/ninja), so any help would be appreciated.
Bye

**Comment by ohlidalp** [comment]
Hi.
The errors are mysterious. Caelum library basically claims OGRE is not included in the build at all, but if that was true, RoR compiled objects would complain, too.

Check if you have any OGRE or Caelum packages in your system, they may confuse the build. Then, delete the `~/.conan/data` directory and run `game.sh` again, and capture all the logs, I need to know if the dependencies actually build on your machine or get downloaded.

@AnotherFoxGuy is it normal that there's `libCaelum.so` in Conan's `package/HASH/lib`? See the "errors" link above.

**Comment by consultit** [comment]
I have no Ogre or Caelum packages installed. 
I deleted  `~/.conan/data` and run `1>log.txt 2>&1 sh game.sh`  so the entire output is in [log.txt](https://github.com/RigsOfRods/ror-linux-buildscripts/files/2967874/log.txt).
Bye

**Comment by ohlidalp** [comment]
This is the important part:
```
Packages
    OGRE/1.11.5@anotherfoxguy/stable:a0fc77a0cb4b7e774fbd552cf19a5d6eed809781 - Download
    OGREdeps/2018-07@anotherfoxguy/stable:587df1d6a993e6eff4d3791612ba383ca625243c - Download
    ogre-caelum/0.6.3@anotherfoxguy/stable:24148172a069be4a7c07c9bb2497f8604bdb903e - Download
```
This means there's something wrong with the downloaded ogre-caelum package. Try forcing a local build by adding `--build=ogre-caelum` to https://github.com/RigsOfRods/ror-linux-buildscripts/blob/master/game.sh#L22

**Comment by consultit** [comment]
In `game.sh` I put
`conan install --build=ogre-caelum --build=missing -u ../../`
I removed `~/.conan/data` and ran again 
`1>log.txt 2>&1 sh game.sh`
unfortunately the problem remains (see [log.txt](https://github.com/RigsOfRods/ror-linux-buildscripts/files/2973693/log.txt))

**Comment by ohlidalp** [comment]
I'm out of ideas, I need to create a Debian VM and test myself.

For now, try building without Caelum by adding `-DROR_USE_CAELUM=OFF` to https://github.com/RigsOfRods/ror-linux-buildscripts/blob/master/game.sh#L24-L28

**Comment by consultit** [comment]
Ok now it builds successfully. 
But I got this other error:
```
...
ninja: error: unknown target 'install'
```
Anyway the game runs successfully starting from within this directory: `/home/consultit/rigs-of-rods-source/rigs-of-rods/0_build/RelWithDebInfo/bin` :ok_hand:
