### ISSUE TITLE
RoRConfig Mismatch

### ISSUE THREAD

**Issue by jadenPete** [RigsOfRods/ror-linux-buildscripts#8]
I followed the build instructions, but when I run RoRConfig, this pops up:

```
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8).
Aborted
```

**Comment by Hiradur** [comment]
compiler, os?

**Comment by Hiradur** [comment]
Is your wxwidget package up to date?

What is your OS and compiler?

**Comment by jadenPete** [comment]
I am using Ubuntu 14.04.4. Two of my PPAs have updated compilers. One is the updated GCC (6), and the other is CMake 3.2

**Comment by jadenPete** [comment]
As of when I'm writing this, my system is up to date

**Comment by Hiradur** [comment]
Did you compile RoR with gcc 6? If so that could be the problem, you should compile with the default gcc version instead.

**Comment by jadenPete** [comment]
Yes I did. OK I will try that
